header:
  license:
    spdx-id: MIT  # 使用 MIT license
    copyright-owner: YOUR_NAME  # 修改为你的名字
    copyright-year: '' # 留空以使用当前年份
    software-name: YOUR_PROJECT_NAME # 修改为你的项目名

  paths-ignore:
    - 'dist'
    - 'licenses'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'
    - '**/node_modules/**'
    - 'package-lock.json'
    - 'yarn.lock'

  comment: on-failure
