header:
  license:
    spdx-id: MIT
    copyright-owner: Chan Meng
    copyright-year: '*'  # 使用 '*' 来自动检测年份
    
  paths:
    - '*.js'
    - 'src/**/*.js'
    - 'LICENSE'  # 添加 LICENSE 文件到检查路径中
    
  paths-ignore:
    - 'node_modules/**'
    - 'dist/**'
    - 'build/**'
    - '**/*.json'
    - '**/*.md'
    - '**/*.yml'
    - '**/*.yaml'
    - '**/*.svg'
    
  comment: on-failure

  language:
    JavaScript:
      extensions:
        - ".js"
      comment_style_id: SlashAsterisk
    # 添加 LICENSE 文件的语言配置
    Plain:
      extensions:
        - ""  # 无扩展名的文件
      filenames:
        - "LICENSE"
      comment_style_id: Plain

dependency:
  files:
    - package.json
