header:
  license:
    spdx-id: MIT  # 使用 MIT license
    copyright-owner: Chan Meng
    copyright-year: '' # 留空以使用当前年份
    software-name: Advanced Neural Network Applications

  paths-ignore:
    - 'dist'
    - 'licenses'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'
    - '**/node_modules/**'
    - 'package-lock.json'
    - 'yarn.lock'

  comment: on-failure
