header:
  license:
    spdx-id: MIT
    copyright-owner: Chan Meng
    content: |
      Copyright (c) ${YEAR} Chan Meng
      
      This software is released under the MIT License.
      See the LICENSE file for details.

  paths-ignore:
    - '.git/**'
    - '.github/**'
    - '**/*.md'
    - '**/*.csv'
    - '**/*.ipynb'
    - 'LICENSE'
    - '.gitattributes'
    - '.gitignore'
    - '*.txt'

  paths:
    - '**/*.go'
    - '**/*.py'
    - '**/*.java'
    - '**/*.js'
    - '**/*.ts'
    - '**/*.css'
    - '**/*.html'

  comment: on-failure
