name: Update License Year

on:
  schedule:
    - cron: '0 0 1 1 *'  # 每年 1 月 1 日运行
  workflow_dispatch:      # 允许手动触发

jobs:
  update-license-year:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get current year
        id: year
        run: echo "year=$(date +%Y)" >> $GITHUB_OUTPUT
      
      - name: Update license year
        run: |
          # 更新 LICENSE 文件
          sed -i "s/Copyright (c) [0-9]\{4\} Chan Meng/Copyright (c) ${{ steps.year.outputs.year }} Chan Meng/" LICENSE
          # 更新 license 模板
          sed -i "s/Copyright (c) [0-9]\{4\} Chan Meng/Copyright (c) ${{ steps.year.outputs.year }} Chan Meng/" .github/license-templates/MIT.txt
      
      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet LICENSE || echo "changes=true" >> $GITHUB_OUTPUT
      
      - name: Create Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: update license year to ${{ steps.year.outputs.year }}"
          title: "chore: update license year"
          body: |
            Automatically update license year to ${{ steps.year.outputs.year }}.
            
            Changes made:
            - Updated year in LICENSE file
            - Updated year in license template
          branch: "chore/update-license-year"
          base: main
          delete-branch: true
